### ISSUE TITLE
Add detailed docs about audio API

### ISSUE THREAD

**Issue by ntut-rick** [ntut-open-source-club/practical-tools-for-simple-design#11]
> Why do we need 2 API to play sound

Cuz Mix_Chunk specifically for handling sound effects, while Mix_Music is intended for background music. The former is well-suited for playing short audio clips. On the other hand, Mix_Music is optimized for seamlessly streaming longer audio tracks, providing efficient decoding and playback of large files.

_Originally posted by @Dragonfly911117 in https://github.com/ntut-open-source-club/practical-tools-for-simple-design/issues/9#issuecomment-1565884584_

**Comment by Dragonfly911117** [comment]
Isn't the doxygen doc enough?
