### ISSUE TITLE
Add Pivot to GameObject

### ISSUE THREAD

**Issue by NOOBDY** [ntut-open-source-club/practical-tools-for-simple-design#112]
Adding a pivot option to `Util::GameObject` could allow users to offset their `m_Drawable` objects. e.g. users could rotate an image around the pivot, some users might find it convenient to anchor the text to the left

**Comment by NOOBDY** [comment]
Expected API:
Implement `glm::vec2 Util::GameObject::GetPivot() const`
Implement `void SetPivot(const glm::vec2 &pivot)`

Expected Behavior:
Before the draw call, the object should calculate offset based on the pivot value

**Comment by wj461** [comment]
I need the cool feture
