### ISSUE TITLE
`Util::Color` need more APIs

### ISSUE THREAD

**Issue by ntut-rick** [ntut-open-source-club/practical-tools-for-simple-design#115]
`Util::Color` have no API can directly set color from pure RGB/A or hex code
like 
`Util::Color(135, 206, 235)`
`Util::Color(135, 206, 235, 200)`
`Util::Color("87ceeb")`
`Util::Color(0x87ceeb)`
`Util::Color(0x87ceeb, alpha = ...)`

**Comment by Error0229** [comment]
Assign me

**Comment by Dragonfly911117** [comment]
@error0229

**Comment by NOOBDY** [comment]
pseudo API code:
```cpp
Util::Color(R,G,B,A)
static Util::FromRGB(R,G,B)
static Util::FromHex(Hex)
```
