### ISSUE TITLE
Module init/quit sections for easy management (or testing)?

### ISSUE THREAD

**Issue by ntut-rick** [ntut-open-source-club/practical-tools-for-simple-design#13]
Is it a good idea to module init/quit sections for easy management (or testing) ?

_Originally posted by @ntut-rick in https://github.com/ntut-open-source-club/practical-tools-for-simple-design/pull/9#discussion_r1209784817_

**Comment by NOOBDY** [comment]
because everything is needed in the final executable so separating it is not necessary
also context probably doesn't need testing because it's only calling 3rd party APIs
