### ISSUE TITLE
Current frame of Animation unexpectedly increases after the pause ends.

### ISSUE THREAD

**Issue by HeavenManySugar** [ntut-open-source-club/practical-tools-for-simple-design#131]
### Problem

When **Visible** is **_False_** and **State** is **_Pause_**, the **current frame** of Animation will increase when **State** switches back to **_Play_**

當Visible為False時且State為Pause的時候，Animation的current frame會在State切回Play後增加

### Steps to reproduce

1. Create an Animation.
2. Set State to Pause, and Visible to false.
3. Wait for a short period of time, then switch it back to play. You will find that the current frame will increase by the number corresponding to the waiting time.
> 
1. 建立Animation 
2. 將他暫停，並隱藏
3. 等待一小段時間，再將它改為撥放，可以發現current frame會增加相應等待時間的數量

### Expected behavior

The **current frame** should not increase

current frame不應該增加

### PTSD version

commit ad63ed87e5252c5d913dc70dcf69e1ac2298054d

### Operating system/version

Windows 11 Pro 22H2 22621.3155

### CMake version

3.27.6

### CMakeCache.txt

[CMakeCache.txt](https://github.com/ntut-open-source-club/practical-tools-for-simple-design/files/14387878/CMakeCache.txt)

### OpenGL Info

```txt
[info] OpenGL Info
 [info]   Vendor: NVIDIA Corporation
 [info]   Renderer: NVIDIA GeForce RTX 4060/PCIe/SSE2
 [info]   Version: 4.1.0 NVIDIA 546.33
 [info]   GLSL Version: 4.10 NVIDIA via Cg compiler
```

**Comment by balaOuO** [comment]
GameObject 在 set visible 為 true 的同時 play 動畫會直接結束

**Comment by ntut-rick** [comment]
#130 might fixes this issue.
if you like to test it in GA following steps:
```sh
cd PTSD
git fetch origin pull/135/head:pr130sm
git checkout pr130sm
# rebuild your project
```
how to restore your submodule:
```sh
cd PTSD
git checkout ad63ed87e5252c5d913dc70dcf69e1ac2298054d
```
