### ISSUE TITLE
Audio Test No Sound

### ISSUE THREAD

**Issue by garry911128** [ntut-open-source-club/practical-tools-for-simple-design#17]
在windows 上跑Test.exe 沒聲音

**Comment by ntut-rick** [comment]
Maybe the same as #16, to be confirm

**Comment by Dragonfly911117** [comment]
I DO have background music and sound effect on my machine.

**Comment by garry911128** [comment]
Confirm is relative path issue, running from the build directory with
```bash
cd out
.\build\x64-Debug\Tests.exe
```
fixes the issue
can merge with #16
