### ISSUE TITLE
Visual Studio 2017 fails to compile

### ISSUE THREAD

**Issue by garry911128** [ntut-open-source-club/practical-tools-for-simple-design#20]
The `cmake_minimum_required` set is too high and Visual Studio 2017 will refuse to compile. IDK if bumping down the version would break things or not.

**Comment by Dragonfly911117** [comment]
Base on [this](https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_makeavailable) and [this](https://cmake.org/cmake/help/latest/policy/CMP0135.html), lower the version will break it.

**Comment by Dragonfly911117** [comment]
Maybe ask the user to [update CMake Version](https://medium.com/@kswong1989/guide-to-visual-studio-2017-cmake-upgrade-hack-583edf440b4e)?

**Comment by Dragonfly911117** [comment]
BTW, the version VS2019's bundle CMake is 3.17, which doesn't have [CMP0135](https://cmake.org/cmake/help/latest/policy/CMP0135.html) as well.

**Comment by NOOBDY** [comment]
It is possible to only set the CMP Policy if the CMake version is higher than 3.24 but IDK if the user can manually upgrade the bundled CMake version in VS 2017

**Comment by NOOBDY** [comment]
Maybe we should recommend users to use the latest version of VS anyway

**Comment by NOOBDY** [comment]
VS 2017 is too old, we will drop support for it and we will bump minimum cmake version required to 3.24
