### ISSUE TITLE
Clang 16 on Windows fails to compile

### ISSUE THREAD

**Issue by NOOBDY** [ntut-open-source-club/practical-tools-for-simple-design#22]
It's the same problem as this https://gitlab.freedesktop.org/freetype/freetype/-/issues/1177
Compiling with GCC and MSVC works fine

**Comment by NOOBDY** [comment]
Currently using clang provided by Visual Studio 2022(a.k.a. C++ Clang tools for Windows) works but I'm still not sure the clear setup steps from a clean install

**Comment by NOOBDY** [comment]
This issue could be resolved by adding setting `CMAKE_RC_FLAGS=-C 1252` during setup
* CLI: `cmake -B build -G Ninja "-DCMAKE_C_COMPILER=clang" "-DCMAKE_CXX_COMPILER=clang++" "-DCMAKE_RC_FLAGS=-C 1252"`

* VSCode in `.vscode/settings.json`:
```json
{
    "cmake.configureArgs": [
        "-DCMAKE_RC_FLAGS=-C 1252"
    ]
}
```

* CLion / Visual Studio: Unknown

---

> Note: using `set(CMAKE_RC_FLAGS ...)` in `CMakeLists.txt` would be ignored according to [CMake](https://cmake.org/cmake/help/latest/envvar/RCFLAGS.html)

Other resources:
* https://github.com/llvm/llvm-project/issues/57367#issuecomment-1227755809
* `llvm-rc -h` output

**Comment by Dragonfly911117** [comment]
> should I close this issue before finding a way to integrate into CLion and Visual Studio?
CLion has no issues building the project.

**Comment by NOOBDY** [comment]
I forgot Visual Studio uses MSVC lol, but does CLion work with Clang?

**Comment by Dragonfly911117** [comment]
I think so.
[ref](https://blog.jetbrains.com/clion/2020/12/setting-up-clang-on-windows/)

**Comment by NOOBDY** [comment]
ok, LGTM, closing
