### ISSUE TITLE
Fix lint/format warnings and `-Werror`

### ISSUE THREAD

**Issue by ntut-rick** [ntut-open-source-club/practical-tools-for-simple-design#23]
1. [ ] Fix clang-tidy and clang-format warnings 
2. [ ] Add `-Werror` in Github Action

**Comment by Dragonfly911117** [comment]
1. [ ] Fix code-style issues

**Comment by Dragonfly911117** [comment]
Should we leave "unused code" and "typo"?

**Comment by Dragonfly911117** [comment]
#30 has merged, so I'm closing the issue.
