### ISSUE TITLE
`Input` is stateless, using a namespace (similar to a logger) could be better than a singleton class.

### ISSUE THREAD

**Issue by ntut-rick** [ntut-open-source-club/practical-tools-for-simple-design#33]
`Input` is stateless, using a namespace (similar to a logger) could be better than a singleton class.

_Originally posted by @ntut-rick in https://github.com/ntut-open-source-club/practical-tools-for-simple-design/pull/30#discussion_r1292301658_

**Comment by Dragonfly911117** [comment]
This is done with #34 so I'm closing this issue.
