### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by ntut-xuan** [ntut-open-source-club/practical-tools-for-simple-design#41]
<img width="1920" alt="image" src="https://github.com/ntut-open-source-club/practical-tools-for-simple-design/assets/69747731/42d1f784-acf8-4446-a301-b8720840d157">

**Comment by NOOBDY** [comment]
commenting this line fixes the issue, but logging functionality would be lost

**Comment by NOOBDY** [comment]
https://registry.khronos.org/OpenGL-Refpages/gl4/html/glDebugMessageCallback.xhtml
`glDebugMessageCallback` is OpenGL 4.3 functionality and macOS only supports up to 4.1, will need to find alternative
