### ISSUE TITLE
Incorrect Git URL & missing `cd` in README

### ISSUE THREAD

**Issue by SArthurX** [ntut-open-source-club/practical-tools-for-simple-design#59]
README has incorrect Git URL and lacks `cd` after cloning.

```diff
-git clone https://ntut-open-source-club/practical-tools-for-simple-design.git
+git clone https://github.com/ntut-open-source-club/practical-tools-for-simple-design.git
+cd practical-tools-for-simple-design

 cmake -B build
 cmake --build build
```

**Comment by Dragonfly911117** [comment]
> The configuration on Ubuntu may have some issue
I realize the step may be just clone it and configure the project with CMake (with clang and clion also). But I still need some packages to make it configure successfully. It could be mentioned on documentation or somewhere ```
sudo apt-get install libgl1-mesa-dev libxext-dev
```

@ntut-xuan 


https://discord.com/channels/1093814266630512681/1093814266630512684/1194683686646452314
