### ISSUE TITLE
request get image width and height

### ISSUE THREAD

**Issue by nonorze-VOXX** [ntut-open-source-club/practical-tools-for-simple-design#79]
# effect
1. ~~default collider size should set image size~~ #68 
2. get width and height which is scaled #85

**Comment by ntut-rick** [comment]
Could read `w,h` from `SDL_Surface` when image load

ref: https://wiki.libsdl.org/SDL2/SDL_Surface

**Comment by ntut-rick** [comment]
> default collider size should set image size

No collider in this framework yet
