### ISSUE TITLE
Got color channel bug on macOS

### ISSUE THREAD

**Issue by ntut-rick** [ntut-open-source-club/practical-tools-for-simple-design#97]
Got color channel bug on macOS
![technology screenshot](https://media.discordapp.net/attachments/953920487371731005/1204782207428984903/IMG_0320.jpg?ex=65d5fbde&is=65c386de&hm=6b33f6282cedc49876b95998291d954d4a00120f125be2cb5ea729a682dbb11f&=&format=webp&width=429&height=573)

_Originally posted by @ntut-rick in https://github.com/ntut-open-source-club/practical-tools-for-simple-design/issues/96#issuecomment-1932068671_

**Comment by NOOBDY** [comment]
will try to fix this when I have access to macOS machine
